{{- if and .Values.ingress.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "health.fullname" . }}-tls
type: kubernetes.io/tls
data:
{{ (.Files.Glob "cert/*").AsSecrets | indent 2 }}
{{- end -}}