apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-selector
  name: node-selector
spec:
  containers:
  - image: busybox
    name: node-selector
    command:
    - "sleep"
    - "3600"
  nodeSelector:
    accelerator: nvidia-tesla-p100
  restartPolicy: Always
