---
apiVersion: v1
kind: Pod
metadata:
  name: app-initcontainer
  labels:
    app: app-initcontainer
spec:
  initContainers:
  - name: setup
    image: busybox
    volumeMounts:
    - name: www
      mountPath: /data
    command:
    - 'sh'
    - '-c'
    - 'echo TEST > /data/index.html'
  containers:
  - name: app
    image: nginx:alpine
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80
  volumes:
  - name: www
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: app-initcontainer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP