# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

k8s_version = "1.23.7"

k8s_control = {
  "control-01" => { :ip => "192.168.56.4", :cpus => 2, :mem => 2048 }
}

k8s_worker = {
  "worker-01" => { :ip => "192.168.56.11", :cpus => 1, :mem => 1024 },
  "worker-02" => { :ip => "192.168.56.12", :cpus => 1, :mem => 1024 }
}


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  k8s_control.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |cfg|

      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/focal64"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.gui = false
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      cfg.vm.provision "shell",
        path: "scripts/common.sh",
        env: {
          "K8S_VERSION" => "#{k8s_version}",
          "HOSTNAME" => "#{hostname}",
          "NODE_IP" => "#{info[:ip]}"
        }

      cfg.vm.provision "shell",
      path: "scripts/init-master.sh",
      env: {
        "K8S_VERSION" => "#{k8s_version}",
        "HOSTNAME" => "#{hostname}",
        "NODE_IP" => "#{info[:ip]}"
      }

    end

  end

  k8s_worker.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |cfg|

      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/focal64"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.gui = false
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      cfg.vm.provision "shell",
      path: "scripts/common.sh",
      env: {
        "K8S_VERSION" => "#{k8s_version}",
        "HOSTNAME" => "#{hostname}",
        "NODE_IP" => "#{info[:ip]}"
      }

      cfg.vm.provision "shell",
      path: "scripts/init-worker.sh",
      env: {
        "K8S_VERSION" => "#{k8s_version}",
        "HOSTNAME" => "#{hostname}",
        "NODE_IP" => "#{info[:ip]}",
        "MASTER_IP" => "192.168.56.4"
      }

    end

  end

end
