apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multicontainer
  name: multicontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multicontainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multicontainer
    spec:
      containers:
      - image: nginx:1.21-alpine
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      initContainers:
      - image: busybox
        name: busybox
        resources: {}
        command:
        - /bin/sh
        args:
        - -c
        - "echo TEST > /data/web/index.html"
        volumeMounts:
        - name: web-content
          mountPath: /data/web
      volumes:
      - name: web-content
        hostPath:
          path: /data/web 

