apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: alpine:3.11
          command: ["sh","-c","sleep 10"] 
      restartPolicy: Never
  backoffLimit: 4

