apiVersion: v1
kind: Pod
metadata:
  name: sleeper
  namespace: default
  labels:
    app: shell
  annotations:
    os: alpine
    version: "3.9"
spec:
  containers:
    - name: main
      image: alpine:3.9
      command: ["sh","-c","while true;do date;sleep 1;done"]

