apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-2
  labels:
    app: test
spec:
  containers:
  - name: sleeper
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: pvc
      mountPath: /etc/foo
  restartPolicy: Never
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: myvolume-4g

