apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-multi-emptydir
  name: pod-multi-emptydir
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: container-1 
    resources: {}
    volumeMounts:
      - name: data
        mountPath: /etc/foo
  - command:
    - sleep
    - "3600"
    image: busybox
    name: container-2 
    volumeMounts:
      - name: data
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: data
      emptyDir: {}
status: {}
