apiVersion: v1
kind: Pod
metadata:
  name: multi-echo
  labels:
    app: echo
spec:
  containers:
  - name: echo-1
    image: busybox
    command:
      - /bin/sh
    args:
      - -c
      - "echo Hello;sleep 3600"
  - name: echo-2
    image: busybox
    command:
      - /bin/sh
    args:
      - -c
      - "echo Hello;sleep 3600" 
  restartPolicy: Never
