--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-single-ng
  version: "1.22"
  region: eu-central-1

availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]

nodeGroups:
  - name: ng-frontend
    instanceType: t3a.large
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    amiFamily: Bottlerocket
    privateNetworking: true
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    disableIMDSv1: true
    labels:
      nodegroup-type: default
