apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-configmap
  name: nginx-configmap
spec:
  containers:
  - image: nginx:1.20.1
    name: nginx-configmap
    env:
      - name: HOSTNAME
        valueFrom:
          configMapKeyRef:
            name: nginx
            key: HOSTNAME
  restartPolicy: OnFailure
