apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-configmap-multi
  name: nginx-configmap-multi
spec:
  containers:
  - image: nginx:1.20.1
    name: nginx-configmap-multi
    envFrom:
      - configMapRef:
          name: nginx-multi
  restartPolicy: OnFailure
