apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secret
  name: pod-secret
spec:
  containers:
  - image: busybox
    command:
      - "sleep"
      - "3600" 
    name: pod-secret
    resources: {}
    volumeMounts:
      - name: secret-vol
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never 
  volumes:
    - name: secret-vol
      secret:
        secretName: mysecret2
status: {}
