apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secret-2
  name: pod-secret-2
spec:
  containers:
  - image: nginx:1.20.1-alpine
    name: pod-secret-2
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2 
            key: secret-2.data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
