apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-resources
  name: pod-resources
spec:
  containers:
  - image: nginx:1.20.1-alpine
    name: pod-resources
    resources: 
      limits:
        cpu: "0.5"
        memory: "100Mi"
      requests:
        cpu: "0.5"
        memory: "100Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
