apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-serviceaccount
  name: pod-serviceaccount
spec:
  serviceAccount: myuser
  containers:
  - image: nginx:1.20.1-alpine
    name: pod-serviceaccount
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
