---

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.22.0-debian-10-r0

command: []
args: []

replicaCount: 2

nodeSelector: {}

containerPorts:
  http: 8080
  https: ""

service:
  type: ClusterIP
  ports:
    http: 80
  targetPort:
    http: http

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPU: ""
  targetMemory: ""

metrics:
  serviceMonitor:
    enabled: false
    namespace: ""
  prometheusRule:
    enabled: false
    namespace: ""
    additinalLabels: {}
