apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-liveness-probe
  name: pod-liveness-probe
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: pod-liveness-probe
    resources: {}
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      exec:
        command:
          - ls
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
