apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-liveness-probe-http
  name: pod-liveness-probe-http
spec:
  containers:
  - image: nginx:1.20.1-alpine
    name: pod-liveness-probe-http
    resources: {}
    ports:
      - containerPort: 80
    readinessProbe:
      httpGet:
        port: 80
        path: /
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
