apiVersion: v1
kind: Namespace
metadata:
  name: rbac 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-manager
  namespace: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: rbac
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager
  namespace: rbac
subjects:
  - apiGroup: ""
    kind: ServiceAccount 
    name: pod-manager
    namespace: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-manager
  namespace: rbac
spec:
  serviceAccountName: pod-manager
  automountServiceAccountToken: true
  containers:
  - name: reader
    image: bitnami/kubectl
    command:
    - /bin/sh
    args:
    - -c
    - "while true;do echo '\nListing pods ...';kubectl get pods -o wide;sleep 5;done"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
